INSERT INTO country (id, ad) VALUES (1, 'Türkiye')
INSERT INTO country (id, ad) VALUES (3, 'United States of America')
INSERT INTO country (id, ad) VALUES (4, 'Germany')
INSERT INTO country (id, ad) VALUES (5, 'Argentina')
INSERT INTO country (id, ad) VALUES (6, 'Australia')
INSERT INTO country (id, ad) VALUES (7, 'Austria')
INSERT INTO country (id, ad) VALUES (8, 'Azerbaijan')
INSERT INTO country (id, ad) VALUES (9, 'Belgium')
INSERT INTO country (id, ad) VALUES (10, 'United Arab Emirates')
INSERT INTO country (id, ad) VALUES (11, 'Brazil')
INSERT INTO country (id, ad) VALUES (12, 'Bulgaria')
INSERT INTO country (id, ad) VALUES (13, 'Algeria')
INSERT INTO country (id, ad) VALUES (14, 'China (PRC)')
INSERT INTO country (id, ad) VALUES (15, 'Denmark')
INSERT INTO country (id, ad) VALUES (16, 'Sweden')
INSERT INTO country (id, ad) VALUES (21, 'Greece')
INSERT INTO country (id, ad) VALUES (23, 'Albania')
INSERT INTO country (id, ad) VALUES (24, 'Canada')
INSERT INTO country (id, ad) VALUES (31, 'Spain')
INSERT INTO country (id, ad) VALUES (32, 'Mexico')
INSERT INTO country (id, ad) VALUES (33, 'Peru')
INSERT INTO country (id, ad) VALUES (34, 'France')
INSERT INTO country (id, ad) VALUES (36, 'Netherlands')
INSERT INTO country (id, ad) VALUES (37, 'Russia')
INSERT INTO country (id, ad) VALUES (38, 'Moldova')
INSERT INTO country (id, ad) VALUES (39, 'Kenya')
INSERT INTO country (id, ad) VALUES (44, 'Iraq')
INSERT INTO country (id, ad) VALUES (49, 'Iran')
INSERT INTO country (id, ad) VALUES (55, 'Italy')
INSERT INTO country (id, ad) VALUES (56, 'Finland')
INSERT INTO country (id, ad) VALUES (57, 'Egypt')
INSERT INTO country (id, ad) VALUES (58, 'Czech Republic')
INSERT INTO country (id, ad) VALUES (59, 'Norway')
INSERT INTO country (id, ad) VALUES (60, 'United Kingdom')
INSERT INTO country (id, ad) VALUES (61, 'Afghanistan')
INSERT INTO country (id, ad) VALUES (62, 'American Samoa')
INSERT INTO country (id, ad) VALUES (63, 'Andorra')
INSERT INTO country (id, ad) VALUES (64, 'Angola')
INSERT INTO country (id, ad) VALUES (65, 'Anguilla')
INSERT INTO country (id, ad) VALUES (66, 'Antarctica')
INSERT INTO country (id, ad) VALUES (67, 'Antigua and Barbuda')
INSERT INTO country (id, ad) VALUES (68, 'Armenia')
INSERT INTO country (id, ad) VALUES (69, 'Aruba')
INSERT INTO country (id, ad) VALUES (70, 'Ascension')
INSERT INTO country (id, ad) VALUES (72, 'Bahamas')
INSERT INTO country (id, ad) VALUES (73, 'Bahrain')
INSERT INTO country (id, ad) VALUES (74, 'Bangladesh')
INSERT INTO country (id, ad) VALUES (75, 'Barbados')
INSERT INTO country (id, ad) VALUES (77, 'Belarus')
INSERT INTO country (id, ad) VALUES (78, 'Belize')
INSERT INTO country (id, ad) VALUES (79, 'Benin')
INSERT INTO country (id, ad) VALUES (80, 'Bermuda')
INSERT INTO country (id, ad) VALUES (81, 'Bhutan')
INSERT INTO country (id, ad) VALUES (82, 'Bolivia')
INSERT INTO country (id, ad) VALUES (83, 'Bosnia &amp; Herzegovina')
INSERT INTO country (id, ad) VALUES (84, 'Botswana')
INSERT INTO country (id, ad) VALUES (85, 'British Virgin Islands')
INSERT INTO country (id, ad) VALUES (86, 'Brunei')
INSERT INTO country (id, ad) VALUES (87, 'Burkina Faso')
INSERT INTO country (id, ad) VALUES (88, 'Burundi')
INSERT INTO country (id, ad) VALUES (89, 'Cambodia')
INSERT INTO country (id, ad) VALUES (90, 'Cameroon')
INSERT INTO country (id, ad) VALUES (91, 'Cape Verde Islands')
INSERT INTO country (id, ad) VALUES (92, 'Cayman Islands')
INSERT INTO country (id, ad) VALUES (93, 'Central African Republic')
INSERT INTO country (id, ad) VALUES (94, 'Chad')
INSERT INTO country (id, ad) VALUES (95, 'New Zealand')
INSERT INTO country (id, ad) VALUES (96, 'Chile')
INSERT INTO country (id, ad) VALUES (97, 'Christmas Island')
INSERT INTO country (id, ad) VALUES (98, 'Cocos-Keeling Islands')
INSERT INTO country (id, ad) VALUES (99, 'Colombia')
INSERT INTO country (id, ad) VALUES (100, 'Comoros')
INSERT INTO country (id, ad) VALUES (101, 'Congo')
INSERT INTO country (id, ad) VALUES (103, 'Cook Islands')
INSERT INTO country (id, ad) VALUES (104, 'Costa Rica')
INSERT INTO country (id, ad) VALUES (105, 'Côte dIvoire (Ivory Coast)')
INSERT INTO country (id, ad) VALUES (106, 'Croatia')
INSERT INTO country (id, ad) VALUES (107, 'Cuba')
INSERT INTO country (id, ad) VALUES (109, 'Curaçao')
INSERT INTO country (id, ad) VALUES (110, 'Cyprus')
INSERT INTO country (id, ad) VALUES (111, 'Diego Garcia')
INSERT INTO country (id, ad) VALUES (112, 'Djibouti')
INSERT INTO country (id, ad) VALUES (113, 'Dominica')
INSERT INTO country (id, ad) VALUES (114, 'Dominican Republic')
INSERT INTO country (id, ad) VALUES (115, 'East Timor')
INSERT INTO country (id, ad) VALUES (116, 'Easter Island')
INSERT INTO country (id, ad) VALUES (117, 'Ecuador')
INSERT INTO country (id, ad) VALUES (118, 'El Salvador')
INSERT INTO country (id, ad) VALUES (119, 'Equatorial Guinea')
INSERT INTO country (id, ad) VALUES (120, 'Eritrea')
INSERT INTO country (id, ad) VALUES (121, 'Estonia')
INSERT INTO country (id, ad) VALUES (122, 'Ethiopia')
INSERT INTO country (id, ad) VALUES (123, 'Falkland Islands (Malvinas)')
INSERT INTO country (id, ad) VALUES (124, 'Faroe Islands')
INSERT INTO country (id, ad) VALUES (125, 'Fiji Islands')
INSERT INTO country (id, ad) VALUES (126, 'French Antilles')
INSERT INTO country (id, ad) VALUES (127, 'French Guiana')
INSERT INTO country (id, ad) VALUES (128, 'French Polynesia')
INSERT INTO country (id, ad) VALUES (129, 'Gabonese Republic')
INSERT INTO country (id, ad) VALUES (130, 'Gambia')
INSERT INTO country (id, ad) VALUES (131, 'Georgia')
INSERT INTO country (id, ad) VALUES (132, 'Ghana')
INSERT INTO country (id, ad) VALUES (133, 'Gibraltar')
INSERT INTO country (id, ad) VALUES (134, 'Greenland')
INSERT INTO country (id, ad) VALUES (135, 'Grenada')
INSERT INTO country (id, ad) VALUES (136, 'Guadeloupe')
INSERT INTO country (id, ad) VALUES (137, 'Guam')
INSERT INTO country (id, ad) VALUES (139, 'Guatemala')
INSERT INTO country (id, ad) VALUES (140, 'Guinea')
INSERT INTO country (id, ad) VALUES (141, 'Guinea-Bissau')
INSERT INTO country (id, ad) VALUES (142, 'Guyana')
INSERT INTO country (id, ad) VALUES (143, 'Haiti')
INSERT INTO country (id, ad) VALUES (144, 'Honduras')
INSERT INTO country (id, ad) VALUES (145, 'Hong Kong')
INSERT INTO country (id, ad) VALUES (146, 'Hungary')
INSERT INTO country (id, ad) VALUES (147, 'Iceland')
INSERT INTO country (id, ad) VALUES (148, 'India')
INSERT INTO country (id, ad) VALUES (149, 'Indonesia')
INSERT INTO country (id, ad) VALUES (150, 'Ireland')
INSERT INTO country (id, ad) VALUES (151, 'Israel')
INSERT INTO country (id, ad) VALUES (152, 'Jamaica')
INSERT INTO country (id, ad) VALUES (153, 'Japan')
INSERT INTO country (id, ad) VALUES (154, 'Jordan')
INSERT INTO country (id, ad) VALUES (155, 'Kazakhstan')
INSERT INTO country (id, ad) VALUES (156, 'Kiribati')
INSERT INTO country (id, ad) VALUES (157, 'Korea (North)')
INSERT INTO country (id, ad) VALUES (158, 'Korea (South)')
INSERT INTO country (id, ad) VALUES (159, 'Kuwait')
INSERT INTO country (id, ad) VALUES (160, 'Kyrgyz Republic')
INSERT INTO country (id, ad) VALUES (161, 'Laos')
INSERT INTO country (id, ad) VALUES (162, 'Latvia')
INSERT INTO country (id, ad) VALUES (163, 'Lebanon')
INSERT INTO country (id, ad) VALUES (164, 'Lesotho')
INSERT INTO country (id, ad) VALUES (165, 'Liberia')
INSERT INTO country (id, ad) VALUES (166, 'Libya')
INSERT INTO country (id, ad) VALUES (167, 'Liechtenstein')
INSERT INTO country (id, ad) VALUES (168, 'Lithuania')
INSERT INTO country (id, ad) VALUES (169, 'Luxembourg')
INSERT INTO country (id, ad) VALUES (170, 'Macao')
INSERT INTO country (id, ad) VALUES (171, 'Macedonia')
INSERT INTO country (id, ad) VALUES (172, 'Madagascar')
INSERT INTO country (id, ad) VALUES (173, 'Malawi')
INSERT INTO country (id, ad) VALUES (174, 'Malaysia')
INSERT INTO country (id, ad) VALUES (175, 'Maldives')
INSERT INTO country (id, ad) VALUES (176, 'Mali Republic')
INSERT INTO country (id, ad) VALUES (177, 'Malta')
INSERT INTO country (id, ad) VALUES (178, 'Marshall Islands')
INSERT INTO country (id, ad) VALUES (179, 'Martinique')
INSERT INTO country (id, ad) VALUES (180, 'Mauritania')
INSERT INTO country (id, ad) VALUES (181, 'Mauritius')
INSERT INTO country (id, ad) VALUES (182, 'Mayotte Island')
INSERT INTO country (id, ad) VALUES (184, 'Midway Island')
INSERT INTO country (id, ad) VALUES (186, 'Mongolia')
INSERT INTO country (id, ad) VALUES (187, 'Montenegro')
INSERT INTO country (id, ad) VALUES (188, 'Montserrat')
INSERT INTO country (id, ad) VALUES (189, 'Morocco')
INSERT INTO country (id, ad) VALUES (190, 'Mozambique')
INSERT INTO country (id, ad) VALUES (191, 'Myanmar')
INSERT INTO country (id, ad) VALUES (192, 'Namibia')
INSERT INTO country (id, ad) VALUES (193, 'Nauru')
INSERT INTO country (id, ad) VALUES (194, 'Nepal')
INSERT INTO country (id, ad) VALUES (195, 'Netherlands Antilles')
INSERT INTO country (id, ad) VALUES (196, 'St. Kitts and Nevis')
INSERT INTO country (id, ad) VALUES (197, 'New Caledonia')
INSERT INTO country (id, ad) VALUES (199, 'Nicaragua')
INSERT INTO country (id, ad) VALUES (200, 'Niger')
INSERT INTO country (id, ad) VALUES (201, 'Nigeria')
INSERT INTO country (id, ad) VALUES (202, 'Niue')
INSERT INTO country (id, ad) VALUES (203, 'Norfolk Island')
INSERT INTO country (id, ad) VALUES (204, 'Northern Mariana Islands')
INSERT INTO country (id, ad) VALUES (205, 'Oman')
INSERT INTO country (id, ad) VALUES (206, 'Pakistan')
INSERT INTO country (id, ad) VALUES (207, 'Palau')
INSERT INTO country (id, ad) VALUES (209, 'Panama')
INSERT INTO country (id, ad) VALUES (210, 'Philippines')
INSERT INTO country (id, ad) VALUES (211, 'Poland')
INSERT INTO country (id, ad) VALUES (212, 'Portugal')
INSERT INTO country (id, ad) VALUES (213, 'Puerto Rico')
INSERT INTO country (id, ad) VALUES (214, 'Qatar')
INSERT INTO country (id, ad) VALUES (215, 'Romania')
INSERT INTO country (id, ad) VALUES (216, 'Rwandese Republic')
INSERT INTO country (id, ad) VALUES (217, 'Samoa')
INSERT INTO country (id, ad) VALUES (218, 'San Marino')
INSERT INTO country (id, ad) VALUES (219, 'São Tomé and Principe')
INSERT INTO country (id, ad) VALUES (220, 'Saudi Arabia')
INSERT INTO country (id, ad) VALUES (221, 'Senegal')
INSERT INTO country (id, ad) VALUES (222, 'Serbia')
INSERT INTO country (id, ad) VALUES (223, 'Seychelles Republic')
INSERT INTO country (id, ad) VALUES (224, 'Sierra Leone')
INSERT INTO country (id, ad) VALUES (225, 'Singapore')
INSERT INTO country (id, ad) VALUES (226, 'Slovakia')
INSERT INTO country (id, ad) VALUES (227, 'Slovenia')
INSERT INTO country (id, ad) VALUES (228, 'Solomon Islands')
INSERT INTO country (id, ad) VALUES (229, 'Somali Democratic Republic')
INSERT INTO country (id, ad) VALUES (230, 'South Africa')
INSERT INTO country (id, ad) VALUES (231, 'Sri Lanka')
INSERT INTO country (id, ad) VALUES (232, 'St. Helena')
INSERT INTO country (id, ad) VALUES (233, 'St. Lucia')
INSERT INTO country (id, ad) VALUES (234, 'St. Pierre &amp; Miquelon')
INSERT INTO country (id, ad) VALUES (235, 'St. Vincent &amp; Grenadines')
INSERT INTO country (id, ad) VALUES (236, 'Sudan')
INSERT INTO country (id, ad) VALUES (237, 'Suriname')
INSERT INTO country (id, ad) VALUES (238, 'Swaziland')
INSERT INTO country (id, ad) VALUES (239, 'Switzerland')
INSERT INTO country (id, ad) VALUES (240, 'Syria')
INSERT INTO country (id, ad) VALUES (241, 'Taiwan')
INSERT INTO country (id, ad) VALUES (242, 'Tajikistan')
INSERT INTO country (id, ad) VALUES (243, 'Tanzania')
INSERT INTO country (id, ad) VALUES (244, 'Thailand')
INSERT INTO country (id, ad) VALUES (245, 'Timor Leste')
INSERT INTO country (id, ad) VALUES (246, 'Togolese Republic')
INSERT INTO country (id, ad) VALUES (247, 'Tokelau')
INSERT INTO country (id, ad) VALUES (249, 'Trinidad &amp; Tobago')
INSERT INTO country (id, ad) VALUES (250, 'Tunisia')
INSERT INTO country (id, ad) VALUES (251, 'Turkmenistan')
INSERT INTO country (id, ad) VALUES (252, 'Turks and Caicos Islands')
INSERT INTO country (id, ad) VALUES (253, 'Tuvalu')
INSERT INTO country (id, ad) VALUES (254, 'Uganda')
INSERT INTO country (id, ad) VALUES (255, 'Ukraine')
INSERT INTO country (id, ad) VALUES (256, 'Uruguay')
INSERT INTO country (id, ad) VALUES (257, 'US Virgin Islands')
INSERT INTO country (id, ad) VALUES (258, 'Uzbekistan')
INSERT INTO country (id, ad) VALUES (259, 'Vanuatu')
INSERT INTO country (id, ad) VALUES (260, 'Vatican City')
INSERT INTO country (id, ad) VALUES (261, 'Venezuela')
INSERT INTO country (id, ad) VALUES (262, 'Vietnam')
INSERT INTO country (id, ad) VALUES (264, 'Wallis and Futuna Islands')
INSERT INTO country (id, ad) VALUES (265, 'Yemen')
INSERT INTO country (id, ad) VALUES (266, 'Zambia')
INSERT INTO country (id, ad) VALUES (267, 'Zanzibar')
INSERT INTO country (id, ad) VALUES (268, 'Zimbabwe')
INSERT INTO country (id, ad) VALUES (270, 'K.K.T.C')
INSERT INTO country (id, ad) VALUES (271, 'Paraguay')
